# DAG 1

In [1]:
print("Hello, World!")

Hello, World!

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer

## Read Data

In [ ]:
df = pd.read_csv('data_01.csv')

## EDA

In [7]:
df.head()

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

In [8]:
print(df.shape)

(199, 6)

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      199 non-null    float64
 1   x2      199 non-null    float64
 2   x3      199 non-null    float64
 3   x4      199 non-null    float64
 4   x5      199 non-null    float64
 5   target  199 non-null    float64
dtypes: float64(6)
memory usage: 9.5 KB
None

In [11]:
# Target
b = df["target"]
b

0      220.173943
1      175.873929
2     -162.270054
3      165.930461
4       43.250511
          ...
194     48.732442
195     -0.346974
196    -30.311940
197    237.660709
198   -260.843988
Name: target, Length: 199, dtype: float64

In [21]:
#X, y = df(return_X_y=True, as_frame=True)

 
# Only choose two variables for our models
#X = X[['x1', 'x2']]
 
# Give the target a descriptive name
#y.name = 'progression'

In [22]:
x = df.drop(
    columns=[ "target"]
)
x

           x1        x2        x3        x4        x5
0    0.743487  1.072825  1.332911 -1.244771  0.344978
1    0.835264  0.202184  0.966480  0.745883 -0.033773
2   -1.103234  0.030615 -0.140385  0.727683 -2.831224
3    1.210186  1.685258 -0.394123  0.719024 -2.166585
4    0.474577  0.647737 -0.451812 -0.409472 -0.051473
..        ...       ...       ...       ...       ...
194  0.506013 -1.546832  1.371920  0.365069  1.217062
195 -0.108058  0.008594 -0.244017  0.624930  0.397292
196 -0.331685  0.763282 -0.046545 -2.077271 -0.441957
197  3.106505  1.060556 -0.709179 -1.876106  0.161476
198 -0.628655 -0.142817 -2.219201 -2.189732  0.720388

[199 rows x 5 columns]

In [24]:
y = df["target"]
y

0      220.173943
1      175.873929
2     -162.270054
3      165.930461
4       43.250511
          ...
194     48.732442
195     -0.346974
196    -30.311940
197    237.660709
198   -260.843988
Name: target, Length: 199, dtype: float64

In [26]:
# first split to hide the test data
x_train_full, x_test, y_train_full, y_test = train_test_split(
    x,
        y,
        test_size=0.2,
        random_state=40
)

# second split from the rest of the whole data
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full,
    y_train_full,
    test_size=0.15,
    random_state=42
)