#### 11. I denna uppgift kommer vi arbeta med kategorisk data. Nominaldata är kategorisk data där kategorierna inte har någon inbördes rangordning. Datasetet mpg som följer med biblioteket seaborn är ett dataset med 398 observationer av bilar. Den beroende variabeln mpg står för miles per gallon och beskriver bilarnas bränsleeffektivitet. Om vi vill träna en regressionsmodell på mpg-datasetet behöver vi hantera de två kategoriska variablerna origin och name. Variabeln origin är en kategorisk variabel med tre olika värden: europe, japan och usa. Den lämpar sig bra för one hot encoding. Variabeln name har 305 unika värden. Skulle vi utföra one hot encoding på den skulle vårt dataset få 305 nya dimensioner vilket inte är så lämpligt i detta fall. Dessutom - tror du att namnet på bilen har något att göra med hur långt den kör på en gallon bensin? Vi ska därför droppa name-kolumnen innan vi börjar träna en modell på datan.

In [2]:
import seaborn as sns
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

##### a) Läs in datasetet mpg med seaborns load_dataset()-funktion

In [3]:
df = sns.load_dataset("mpg")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

#### Datasetet har:
    - Datatyper i datata setet delas i två olika typer:
        - numerikska värden(float + int).
        - categoriska värden (stringär).
    - variabeln horsepower har 6 saknade värden.

# b) Droppa rader med saknade värden med dropna()-metoden.

In [5]:
df = df.dropna()

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64
 7   origin        392 non-null    str
 8   name          392 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 30.6 KB

In [7]:
df["origin"]

0         usa
1         usa
2         usa
3         usa
4         usa
        ...
393       usa
394    europe
395       usa
396       usa
397       usa
Name: origin, Length: 392, dtype: str

# c) Droppa kolumnen name.

In [8]:
df = df.drop(columns=["name"])
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

# d) Utför en dummy-variable-encoding på origin-kolumnen med pandas get_dummies()-funktion. Ange drop_first=True så att vi får 2 nya kolumner istället för 3.

In [9]:
df = pd.get_dummies(df, columns= ["origin"], dtype =str , drop_first=True)
df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64
 7   origin_japan  392 non-null    str
 8   origin_usa    392 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 30.6 KB

# e) Dela upp datasetet i X och y, med mpg som den beroende variabeln y.

In [10]:
x = df.drop(columns=["mpg"])
y = df["mpg"]

# f) Dela upp datasetet i träning- och testset.

### Notera vad säger uppgiften:
* Varför skulle vi inte dela upp datan i 3 delar (train - validation - test)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val , test_size=0.3, random_state=42)

# g) Träna en linjär regressionsmodell på träningsdatan och utvärdera den på testdatan.

In [13]:
lin_reg = LinearRegression()

lin_reg.fit(x_train, y_train)

ValueError: could not convert string to float: 'False'